<?php session_start();?>
<?php include('menu.php');
  header( 'content-type: text/html; charset=ISO-8859-1' );
?>
    <section id="rest" class="container-fluid content-section text-center">
        <div class="row">
            <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
                <div class='col-lg-6 col-md-6 col-sm-8 col-xs-12 col-lg-offset-3 col-md-offset-3 col-sm-offset-2' id="pages-mentions">
                    <br><br><br><br><br><br>
                    <h1 class="glowingtext">Foire aux Questions</h1>
<h2 class="text-left"></h2>
<p class="text-left">https://docs.google.com/document/d/1nVNhI0Sk4UF4f3LKHoAQF2lLaQVB4SyPqMP_q3j-Nk4/edit#</p>
<h2 class="text-left">En cours de mise en page</h2>
<p class="text-left">
	Juin 2016
http://www.letsplayce.com
Veuillez lire attentivement les présentes conditions générales d’utilisation du service proposé par la société PLAYCE dans le cadre du site : « http://www.letsplayce.com » (ci-après les « CGU ») et ce, préalablement à toute utilisation de celui-ci. L’utilisation du Service, implique Votre acceptation préalable des CGU dans leur version en vigueur. Si vous avez des questions sur celles-ci, n'hésitez pas à nous contacter par mail ou en nous écrivant aux adresses suivantes : contact@letsplayce.com 

1. INFORMATIONS LEGALES
1.1 OBJET DES CGU
La société PLAYCE propose sur son site « http://www.letsplayce.com » (ci-après le « Site »), un service permettant aux Utilisateurs de commander des services de dépannage d’urgence à domicile ou de travaux de rénovation et d'être mis en relation avec un artisan ou professionnel sélectionné par PLAYCE dans le cadre et respect des conditions définies dans les présentes CGU.
Les présentes Conditions Générales d’Utilisation (CGU) décrivent les conditions selon lesquelles PLAYCE propose l'accès à ses services. L’accès et l’utilisation du service depuis le Site valent acceptation pleine, entière et sans réserve des présentes CGU par tout particulier et tout professionnel. Les présentes CGU sont donc pleinement opposables aux particuliers et aux professionnels.
PLAYCE se réserve le droit de modifier à n'importe quel moment les présentes CGU. PLAYCE mettra alors à disposition des Visiteurs les nouvelles CGU et ce par tout moyen au choix de la Société ; toute utilisation du Service par l’Utilisateur et/ou toute navigation sur le Site par le Visiteur, après publication des CGU modifiées valant acceptation par ces derniers des nouvelles CGU.
PLAYCE vous conseille de d'archiver les présentes CGU applicables au moment de l’utilisation du Site et de la passation de de la Commande.
1.2 IDENTIFICATION DE L'EDITEUR
Le site www.letsplayce.com est édité par la société PLAYCE, SAS, France, au capital de 117 030,60 euros, dont le siège social est 26 rue Damrémont, 75018 Paris, immatriculée au registre du commerce et des sociétés de Paris sous le numéro 795 093 319 – N° de TVA Intracommunautaire : FR 14 795093319. L’éditeur est joignable à l’adresse électronique suivante :contact@letsplayce.com.
1.3 DIRECTEUR DE LA PUBLICATION
Le directeur de la publication du Site Internet letsplayce.com est Monsieur Clément Faivre, Chef de projet de l’agence LEON.



1.4 CONTACTER LA SOCIETE
L'Utilisateur a la possibilité de prendre contact auprès de la Société :
Par lettre simple à l'adresse indiquée à l'article 1.2 ci-dessus ;
Par courrier électronique en utilisant l’adresse mail : contact@letsplayce.com

1.5 HEBERGEUR DU SITE INTERNET
Le site letsplayce.com est hébergé par la société OVH, SAS au capital de 10 000 000 €, immatriculée au Registre du Commerce et des Sociétés de Roubaix – Tourcoing sous le numéro 424 761 419 00045 - Code APE 6202A - N° TVA : FR 22 424 761 419 - et dont le siège social est situé au 2 rue Kellermann - 59100 Roubaix – France.
2. DEFINITIONS
«Charte Qualité» désigne l'ensemble des engagements que les Professionnels s'engagent à respecter envers tout utilisateur en matière de qualité de service. Ces engagements sont exposés sur le Site.
«Commande» désigne toute demande de Prestation(s) effectuée et renseignée par l’Utilisateur en remplissant ses Coordonnées, de mise en relation par PLAYCE auprès d’un Professionnel.
«Conditions Générales d’Utilisation» ou «CGU» désigne le présent document ainsi que toute modification ultérieure effectuée par PLAYCE, et ce conformément à l’article 1.1 des présentes CGU.
«Coordonnées» désigne les informations renseignées par tout Utilisateur et collectées par PLAYCE lors de l’utilisation du Service.
«Devis Final» désigne le(s) document(s) identifiant l’Utilisateur, la/les Prestation(s) dans le cadre du Service, ainsi que les conditions tarifaires applicables, la référence aux présentes CGU. Tout Devis Final doit impérativement être validé par le Professionnel et l’Utilisateur.
«Devis Provisoire» désigne la fourchette du tarif de la/des Prestations commandée(s) par l’Utilisateur et exposée par PLAYCE à titre provisoire à ce dernier lors de l'expression du besoin par l'Utilisateur. Un Devis sera considéré comme Provisoire tant qu'il n'aura pas été validé par le Professionnel et l'Utilisateur.
«Membre» désigne tous les utilisateurs du site qui possèdent un compte personnel sur le site, qu’ils soient particuliers ou professionnels.
«Parties» désigne collectivement PLAYCE, le Professionnel et le Visiteur dans le cadre de la navigation sur le Site, et PLAYCE, le Professionnel et l’Utilisateur, dans le cadre de l’utilisation du Service.
«Professionnel» désigne tout artisan, prestataire ou entreprise sélectionné par PLAYCE pouvant répondre à une Commande émise par l’Utilisateur.
«Prestations» désigne les services de dépannage ou de travaux proposés par le Professionnel dans le cadre du Service.
«Profil»: désigne les informations publiques, accessibles aux utilisateurs, et présentées sur la fiche d'un membre.
«Référence» désigne le numéro de commande communiqué par PLAYCE sur le Site lors de la passation de toute Commande. Elle permet notamment à l’Utilisateur d'accéder à l'état d'avancement de sa Commande, et à son historique une fois celle-ci réalisée.
« Service » désigne le service d’intermédiation proposé aux Utilisateurs par PLAYCE. Ce service comprend notamment l’accès et le droit d’utilisation du Site permettant de commander une Pres ration.
«Site» désigne le site internet accessible via l’adresse url https://www.letsplayce.com à partir de laquelle le Service est disponible.
«Territoire» désigne la France métropolitaine.
«PLAYCE» désigne PLAYCE, société par actions simplifiée au capital de 117.030,60 euros, dont le siège social est situé 26, rue Damrémont, 75018 Paris, immatriculée au Registre du Commerce et des Sociétés de Paris sous le numéro 795 093 319, qui détient les droits de propriété exclusifs sur le Site.
«Utilisateur» désigne toute personne qui recherche un Professionnel pour faire réaliser une Prestation et passe Commande dans le cadre du Site et/ou de l’Application Mobile.
«Visiteur» désigne toute personne naviguant sur le Site mais n'utilisant pas forcément le service.
3. CONDITIONS D'INSCRIPTION ET D'ELIGIBILITE
Notre service est réservé aux personnes juridiquement capables de souscrire des contrats en droit français. Si le compte d'un utilisateur a été temporairement ou définitivement suspendu, il n'est plus autorisé à utiliser nos services. Un compte PLAYCE et un pseudonyme ne peuvent être transférés ou cédés à des tiers, sous quelque forme que ce soit.
Le Visiteur garantit par ailleurs avoir la pleine capacité juridique pour utiliser le Service, et notamment :
Si le Visiteur utilise le Service en qualité de personne physique - celui-ci garantit avoir la majorité légale et ne pas être sous tutelle ou curatelle. Les mineurs sont autorisés à naviguer sur le Site et/ou utiliser le Service sous la surveillance d’un adulte
Si le Visiteur - personne physique -  utilise le Service au nom et pour le compte d’une entité juridique - celui-ci garantit disposer des pouvoirs nécessaires pour engager ladite entité.
Par ailleurs, l’Utilisateur ne doit pas être un concurrent de PLAYCE et n’utilisera le Service ni pour concurrencer PLAYCE, ni de manière frauduleuse et/ou en général de manière à nuire aux intérêts de PLAYCE.
Enfin, l'utilisation du Service implique que les Visiteurs respectent les pré-requis suivants :
Disposer d'une connexion Internet ou d'un abonnement permettant l'accès au site et dont l'utilisateur supportera seul les frais associés.
Disposer d'un modèle d'ordinateur portable ou de Téléphone Mobile compatible avec la version actuelle et toute version ultérieure du Service.
Il est acquis que PLAYCE ne saurait en aucun cas être tenu responsable en cas d’utilisation du Service par des personnes ne répondant pas aux Pré-requis.
4. DESCRIPTION DU SERVICE
Le Service proposé par PLAYCE à pour objectif de mettre en relation des personnes ayant besoin de services de dépannage d’urgence ou de travaux avec un professionnel disposant du savoir-faire nécessaire pour réaliser les prestations commandées dans le cadre de l’utilisation du Service. Les Professionnels sélectionnés par PLAYCE sont spécialisés en particulier dans les domaines de la plomberie, la serrurerie, l’électricité, la peinture, la menuiserie, la maçonnerie et/ou la vitrerie. Ils sont sélectionnés selon des critères précis de rapidité d’intervention, de réactivité, de qualité et de fiabilité des Prestations, et ce afin de faire bénéficier les Utilisateurs des meilleures conditions d’intervention dans le cadre du Service.
En particulier, les Professionnels sélectionnés par PLAYCE ont tous accepté la Charte Qualité figurant sur le Site et ont répondu aux conditions administratives d’éligibilité nécessaires pour proposer leurs Prestations dans le cadre du Service.
Il est précisé que PLAYCE agit en tant que simple intermédiaire. PLAYCE ne fournit à ce titre aucune Prestation au titre d’une Commande passée sur le site et n’est pas partie au contrat conclu entre les Utilisateurs et les Professionnels.
5. MODALITES D’UTILISATION DU SERVICE ET DE PASSATION DE COMMANDE
Le Service est consenti à titre gratuit. Il est d'ailleurs précisé à l'Utilisateur que PLAYCE, pour chaque Commande passée sur le site et au titre de sa fonction d'intermédiaire apporteur d'affaire, facture le Professionnel sur la base d'une commission correspondant à un pourcentage du montant facturé par le Professionnel à l'Utilisateur dans le cadre de la Commande.
Chaque Utilisateur peut passer Commande depuis le Site, à condition de respecter les Prérequis et les conditions d’éligibilités définis à l’article 3 des présentes CGUS.
La procédure de passation de Commande sur le Site dépend de la nature des travaux que l'Utilisateur souhaite réaliser. Si le besoin de l'Utilisateur concerne un dépannage d'urgence (serrurerie, plomberie, électricité):
L'Utilisateur renseigne ou sélectionne les champs prédéfinis dans le questionnaire à choix multiple proposés par PLAYCE et permettant d’identifier aussi précisément que possible son besoin. C'est sur la base de ce besoin que PLAYCE pourra établir une fourchette tarifaire du coût de la Prestation.
Une fois la case « valider » cochée, PLAYCE transmet sur son site à l’Utilisateur un Devis le coût des travaux en fonction de la grille tarifaire des Professionnels disponibles et qualifiés pour réaliser la/les Prestation(s). S'il souhaite bénéficier de la/des Prestation(s), l'Utilisateur valide la proposition effectuée par PLAYCE.
L’Utilisateur renseigne ensuite un formulaire relatif à ses Coordonnées qui contient notamment prénom, nom, numéro de téléphone, adresse électronique et adresse postale. Ces données sont obligatoires car nécessaires pour assurer une bonne réalisation de la ou des Prestation(s). L’Utilisateur garantit l’exactitude et le caractère exhaustif des données requises dans les champs appropriés.
Pour le paiement, PLAYCE offre la possibilité d'un paiement en ligne sécurisé par carte bancaire. Pour bénéficier de ce service, l'Utilisateur doit au préalable cocher la case: «je certifie avoir lu accepté les Conditions Générales d'Utilisation du Service». l’Utilisateur est alors dirigé vers la page de paiement en ligne sécurisé par carte bancaire, ce service étant conforme aux standards de sécurité requis par les normes de sécurité bancaire et est assuré par un système de transaction proposé par un prestataire de PLAYCE. L’Utilisateur remplit alors ses coordonnées bancaires pour autoriser sur son compte bancaire le blocage de la somme équivalant au plafond de la fourchette tarifaire proposé par PLAYCE dans le Devis Provisoire. Une fois la transaction validée, PLAYCE transmet à l'Utilisateur un numéro de référence unique à l'aide duquel ce dernier pourra consulter à tout moment l'état d'avancement de sa Commande.
L'Utilisateur a également la possibilité de payer sa Commande sur place, par chèque ou carte bancaire. Pour bénéficier de ce service, l'Utilisateur doit au préalable cocher la case : «je certifie avoir lu accepté les Conditions Générales d'Utilisation du Service». Une fois sa commande validée, le processus explicité à l'étape 4 ci-dessus est également applicable. Il est noté que PLAYCE se réserve le droit de contrôler l’identité de l'Utilisateur en cas de paiement par chèque.
Si l’utilisateur opte pour le paiement sur place, par chèque ou par carte bancaire (via un Terminal de Paiement Électronique) : après avoir coché la case : «je certifie avoir lu accepté les Conditions Générales d'Utilisation du Service» et après validation de sa commande, la Commande est prise en compte. PLAYCE fournit à l’Utilisateur sur le Site sa Référence lui permettant, à l’aide de son numéro de téléphone, de vérifier sur le Site l’état d’avancement de sa Commande. Une pièce d’identité pourra être demandée pour tout paiement à domicile par chèque.
Un récapitulatif de la commande est envoyé aux Professionnels sélectionné par PLAYCE. Une fois la demande acceptée par un Professionnel, l'Utilisateur reçoit une confirmation de la prise en charge de la Prestation avec les coordonnées du Professionnel sélectionné, une date et une heure d'intervention. Le Professionnel acceptant la demande s'engage alors à honorer le rendez-vous. Le Professionnel s’engage également à contacter l’Utilisateur par téléphone au numéro de téléphone communiqué par ce dernier dans les meilleurs délais suivant la validation de sa Commande et ce pour définir les modalités de réalisation des Prestations et/ou obtenir toute précision utile sur les travaux à réaliser. Le Professionnel s'engage enfin dans le cadre de la formalisation de son Devis Final, à ne dépasser le plafond du Devis Provisoire transmis par PLAYCE qu’après autorisation préalable de l’Utilisateur et qu'en cas de motifs le justifiant, et notamment une erreur dans le diagnostic effectué par l'Utilisateur lors de la passation de la Commande. L'Utilisateur et le Professionnel s'engagent à mettre a jour le montant du Devis Final sur le site, notamment en cas de modification de celui-ci intervenant au cours de la réalisation de la Prestation. Il est rappelé que l’Utilisateur, dans le cas de la conclusion d'un Devis Final avec un Professionnel, est soumis aux CGU dudit Professionnel.
Le Professionnel sélectionné réalise la Prestation à la date et à l'heure convenues avec l'Utilisateur. PLAYCE fera son possible pour rappeler au Professionnel la programmation du rendez-vous mais ne saurait être tenu responsable en cas de non-intervention ou de retard du Professionnel dans les délais impartis. Le Professionnel s’engage à signaler et à transmettre le le Devis Final à PLAYCEpar tout moyen que ce soit. Enfin, en cas de modification du Devis Final engendrant un dépassement du montant plafond communiqué dans le Devis Provisoire, l'Utilisateur accepte que PLAYCE soit autorisé à modifier le montant bloqué initialement lors de l’étape 4.
Une fois le Devis Final validé et signé, le Professionnel réalise la Prestation exposée dans le Devis Final.
Sans réclamation portée par l'Utilisateur à l'attention de PLAYCE dans les 72 heures suivant la réalisation de la Prestation, PLAYCE prélève sur le compte bancaire de l’Utilisateur la somme indiquée dans le Devis Final du Prestataire.Le versement du montant des travaux sur le compte du professionnel ne sera déclenché qu'à l'issue de ces 72 heures.
Si le besoin de l'Utilisateur concerne d'autres types de travaux (peinture, menuiserie, maçonnerie et/ou vitrerie ) :
L'Utilisateur renseigne ou sélectionne les champs prédéfinis dans le questionnaire à choix multiples proposé par PLAYCE et permettant d’identifier aussi précisément que possible son besoin.
Une fois la case «valider» cochée, et si les informations renseignées par l'Utilisateur sont correctes PLAYCE transmet sur son site à l’Utilisateur un Devis Provisoire estimant le coût des travaux en fonction de la grille tarifaire des Professionnels disponibles et qualifiés pour réaliser la/les Prestation(s). S'il souhaite bénéficier de la/des Prestation(s), l'Utilisateur valide la proposition effectuée par PLAYCE. Si PLAYCE n'est pas en mesure de définir un chiffrage, il transmet la demande à 3 professionnels sélectionnés par ses soins.
L’Utilisateur renseigne ensuite un formulaire relatif à ses Coordonnées qui contient notamment prénom, nom, numéro de téléphone, adresse électronique et adresse postale. Ces données sont obligatoires car nécessaires pour assurer une bonne réalisation de la ou des Prestation(s). L’Utilisateur garantit l’exactitude et le caractère exhaustif des données requises dans les champs appropriés. Un numéro de référence est alors communiqué à l'Utilisateur pour lui permettre notamment l'accès à ses devis.
Les Professionnels, sélectionnés par PLAYCE dans le cadre de l'établissement de ses devis, s'engagent à transmettre un chiffrage des travaux demandés par l'Utilisateur dans les 48 heures. Les chiffrages définis sont signalés et transmis à l'Utilisateur sur le Site. L'Utilisateur peut choisir le Devis Provisoire qui lui convient sur le Site et après y avoir accédé via le numéro de référence de la transaction.
Une fois la Demande validée, un acompte correspondant à un pourcentage du montant plafonné du Devis Provisoire est exigible à l'Utilisateur. PLAYCE offre à ce titre la possibilité du paiement en ligne sécurisé par carte bancaire. Pour bénéficier de ce service, l'Utilisateur doit au préalable cocher la case : «je certifie avoir lu accepté les Conditions Générales d'Utilisation du Service». l’Utilisateur est alors dirigé vers la page de paiement en ligne sécurisé par carte bancaire, ce service étant conforme aux standards de sécurité requis par les normes de sécurité bancaire et est assuré par un système de transaction proposé par un prestataire de PLAYCE. L’Utilisateur remplit alors ses coordonnées bancaires pour autoriser sur son compte bancaire le blocage de la somme équivalant à l'acompte.
Un récapitulatif de la commande est envoyé aux Professionnels sélectionné par PLAYCE. Une fois la demande acceptée par un Professionnel, l'Utilisateur reçoit une confirmation de la prise en charge de la Prestation avec les coordonnées du Professionnel sélectionné, une date et une heure d'intervention. Le Professionnel acceptant la demande s'engage alors à honorer le rendez-vous. Le Professionnel s’engage également à contacter l’Utilisateur par téléphone au numéro de téléphone communiqué par ce dernier dans les meilleurs délais suivant la validation de sa Commande et ce pour définir les modalités de réalisation des Prestations et/ou obtenir toute précision utile sur les travaux à réaliser. Le Professionnel s'engage enfin dans le cadre de la formalisation de son Devis Final, à ne dépasser le plafond du Devis Provisoire transmis par PLAYCE qu’après autorisation préalable de l’Utilisateur et qu'en cas de motifs le justifiant, et notamment une erreur dans le diagnostic effectué par l'Utilisateur lors de la passation de la Commande. L'Utilisateur et le Professionnel s'engagent à mettre à jour le montant du Devis Final sur le site, notamment en cas de modification de celui-ci intervenant au cours de la réalisation de la Prestation. Il est rappelé que l’Utilisateur, dans le cas de la conclusion d'un Devis Final avec un Professionnel, est soumis aux CGU dudit Professionnel.
Le Professionnel sélectionné réalise la Prestation dans les délais convenus avec l'Utilisateur. Le Professionnel s’engage à signaler et à transmettre le le Devis Final à PLAYCE par tout moyen que ce soit.
Une fois le Devis Final validé et signé, le Professionnel réalise la Prestation exposée dans le Devis Final.
Le paiement du solde de la Prestation est effectué par l'Utilisateur directement au Professionnel, par chèque ou par carte bancaire (via un Terminal de Paiement Électronique), après avoir coché la case : «je certifie avoir lu accepté les Conditions Générales d'Utilisation du Service». Une pièce d’identité pourra être demandée pour tout paiement à domicile par chèque. Il est rappelé que le Professionnel s’engage à signaler et à transmettre le le Devis Final à PLAYCE par tout moyen que ce soit.
Si l’Utilisateur le souhaite, il a la possibilité de vérifier l’état d’avancement de sa Commande sur le Site et/ou sur l’Application Mobile à l’aide de sa Référence et son numéro de téléphone en cliquant sur l’onglet y afférent sur le Site.
Sans réclamation portée par l'Utilisateur à l'attention de PLAYCE dans les 72 heures suivant la réalisation de la Prestation, PLAYCE prélève sur le compte bancaire de l’Utilisateur la somme indiquée dans le Devis Final du Prestataire.Le versement du montant des travaux sur le compte du professionnel ne sera déclenché qu'à l'issue de ces 72 heures.
6. UTILISATION DES COORDONNEES DE L’UTILISATEUR
Une fois inscrit sur le site, l'Utilisateur a la possibilité de paramétrer le ou les canaux de communication au travers duquel il souhaite être joint (SMS, mail et/ou téléphone), notamment pour la confirmation ou le rappel d'un rendez- vous avec un Professionnel suite au passage d'une commande. Ce paramétrage est matérialisé par des cases à cocher correspondant à chaque canal. Il est rappelé qu'une case cochée vaut acceptation de l'utilisation de ce canal et ce pour quelconque communication que PLAYCE jugerait utile d'assurer dans le cadre de la réalisation de sa Commande.
L’Utilisateur reconnaît être seul et pleinement responsable de la protection de la confidentialité de ses Coordonnées fournies lors de la passation de sa Commande. Il est rappelé à l'Utilisateur qu'il ne doit en aucun cas autoriser des tiers à utiliser ses Coordonnées. Il est à ce titre responsable de l'utilisation éventuelle de ses coordonnées dans le cadre de l'accès par un tiers à l’ordinateur et/ou au téléphone mobile depuis lequel/lesquels le Service est accessible.
Dans ce contexte, chaque Utilisateur admet et accepte que la passation d'une Commande en utilisant ses Coordonnées soit réputée avoir été effectuée par lui-même. En cas de doute, ou si l’Utilisateur a une quelconque raison de penser que ses Coordonnées ne sont plus protégées, il doit, dans la mesure du possible, le signaler à PLAYCE à l'adresse suivante :contact@playce.com.
7. OBLIGATIONS ET ENGAGEMENTS DES PARTIES
7.1 OBLIGATIONS ET ENGAGEMENTS DE PLAYCE
PLAYCE assure à distance et par voie électronique la fourniture d'un Service de mise en relation via des services de communication électronique et n’emploie directement ou indirectement aucun des professionnels inscrits sur le site.
PLAYCE s’engage à transmettre un Devis Provisoire à l’Utilisateur en fonction de la grille tarifaire des Professionnels uniquement s'il dispose des informations nécessaires à son établissement. Il s'engage par ailleurs à mettre en relation l’Utilisateur avec le Professionnel sélectionné afin que ce dernier réalise la/les Prestations ayant fait l’objet de la Commande.
PLAYCE garantit son indépendance vis-à-vis des Professionnels et sa neutralité dans la sélection de ceux-ci au regard du besoin et de la Commande de l'Utilisateur.
PLAYCE n'a pas pour obligation légale d'identifier les utilisateurs à leur connexion au site ou de garantir la véracité des contenus édités par les Utilisateurs, qui reste sous leur responsabilité exclusive. Dans l’incapacité technique de réaliser ses contrôles, PLAYCE ne peut s’engager contractuellement à assurer ces prestations.
PLAYCE s’engage cependant à exercer une modération des photos et textes rédigés par les Utilisateurs afin de garantir le respect des lois et des bonnes mœurs.
PLAYCE se dégage de toute responsabilité lors de rencontres entre Membres du site suite à l'utilisation de ses Services. Les Utilisateurs du service PLAYCE nous dégagent de toute responsabilité en cas de litige entre plusieurs Membres pour toute réclamation, et tout dommage présent ou futur, présumé ou non, constaté ou non, résultant de manière directe ou indirecte de ces réclamations.
7.2 OBLIGATIONS ET ENGAGEMENTS DES UTILISATEURS
L’Utilisateur s’engage à :
Respecter les Prérequis et à communiquer à PLAYCE ses Coordonnées exactes et garantit leur exactitude;
Informer PLAYCE de toute modification portant sur le contenu de sa Commande et/ou de ses Coordonnées le cas échéant;
Ne pas utiliser PLAYCE à des fins professionnelles ou commerciales ou non privées ;
Ne pas utiliser le service à des fins de racolage ou de prostitution ;
Ne pas communiquer, transmettre ou diffuser des faux contenus, des contenus diffamatoires, injurieux, obscènes, ou violents. Tout contenu politique, xénophobe ou contraire aux lois et règlements en vigueur, aux droits personnes ou aux bonnes mœurs ;
Ne diffuser aucune information ou contenu pouvant entraver le bon fonctionnement du site. PLAYCE se réserve ainsi  le droit de supprimer les messages ou de réaliser toute action jugée nécessaire pour assurer une qualité d'utilisation normale du Service ;
Pour les Utilisateurs mineurs, ne pas utiliser les Services sans avoir au préalable obtenu le consentement explicite de leurs responsables légaux.
Il est rappelé en outre que l'Utilisateur est seul responsable des informations qu'il communique lors de sa Commande et qui permettent la définition du Devis Provisoire par PLAYCE. La Société décline toute responsabilité en cas d’omission ou d’erreur de l’Utilisateur lorsque ce dernier effectue sa Commande.
En cas de non-respect d’une des obligations ci-dessus, PLAYCE se réserve le droit de supprimer le compte du Membre concerné.
L’utilisateur inscrit peut en outre publier des avis sur le Site. L’utilisateur s’engage expressément à respecter les dispositions légales et réglementaires en vigueur. En outre, le contenu publié par l’utilisateur ne doit porter atteinte ni aux personnes (injures, diffamation, etc.), ni au respect de la vie privée, et doit se conformer au respect de l’ordre public et des bonnes mœurs (incitation à la haine, contenu pornographique, etc.).
En publiant l’avis sur le Site, l’utilisateur s’engage à donner une opinion personnelle et certifie qu’aucun lien commercial ou personnel avec les sociétés ou prestataires concernés par l’avis n’existe. L’utilisateur accepte en outre que son contenu soit publié et consulté sur le Site, et puisse être utilisé à des fins de communication par PLAYCE ou ses partenaires.
L’utilisateur accepte également que son contenu fasse l’objet d’une modération par PLAYCE et, qu’en cas de non- respect des dispositions des présentes CGU ou de violation des lois en vigueur, qu’une résiliation de son compte, sans préavis ni indemnité, peut être opérée par PLAYCE
7.3 OBLIGATIONS ET ENGAGEMENTS DES PROFESSIONNELS
Dans le cadre du Service, les Professionnels s’engagent à :
Respecter les conditions d’éligibilité au Service ;
Respecter la Charte Qualité figurant sur le Site ;
Respecter les réglementations applicables en vigueur, en particulier concernant leurs obligations fiscales et sociales ;
Appliquer des tarifs conformes à leur Devis Final ;
Communiquer à l’Utilisateur ses conditions générales de vente le cas échéant.
Dans l’hypothèse où le Professionnel ne satisfait pas tout ou partie des obligations ci-dessus, PLAYCE se réserve le droit d’exclure ce dernier du Service selon les modalités prévues dans le contrat signé avec ce dernier.
Le Professionnel inscrit peut en outre répondre à des avis publiés par des Utilisateurs ayant eu recours à ses services dans le cadre d'une Prestation effectuée sur le Site. Le Professionnel s’engage expressément à respecter les dispositions légales et réglementaires en vigueur. En outre, le contenu publié par le Professionnel ne doit porter atteinte ni aux personnes (injures, diffamation, etc.), ni au respect de la vie privée, et doit se conformer au respect de l’ordre public et des bonnes mœurs (incitation à la haine, contenu pornographique, etc.).
En publiant l’avis sur le Site, Le Professionnel accepte en outre que son contenu soit publié et consulté sur le Site, et puisse être utilisé à des fins de communication par PLAYCE ou ses partenaires.
Par ailleurs les professionnels s’interdisent de déposer ou faire déposer par des tiers des avis sur des concurrents dans le but de porter atteinte à la réputation d’un autre professionnel. Tout comportement déloyal fera l’objet des mêmes sanctions que celles appliquées pour le dépôt d’un faux avis.
Le Professionnel accepte également que son contenu fasse l’objet d’une modération par PLAYCE et, qu’en cas de non-respect des dispositions des présentes CGU ou de violation des lois en vigueur, qu’une résiliation de son compte, sans préavis ni indemnité, peut être opérée par PLAYCE.
8. GARANTIES
L'Utilisateur accepte que le service est mis à disposition des Utilisateurs en l'état. PLAYCEne saurait garantir quelconque conséquence du site ainsi que celles pouvant provenir des Prestations assurées ou des Services rendus par les Professionnels.
Par ailleurs, PLAYCE ne peut garantir que le Service soit conforme aux exigences de l'Utilisateur et que la qualité des Prestations assurées par les Professionnels sélectionnés répondent à ses attentes. De même, Les Utilisateurs ne peuvent attendre du Site qu'il fonctionne de manière permanente sans erreur de fonctionnement ou d'exploitation.
Aucun avis ou information, écrit ou oral, que l’Utilisateur obtiendra de PLAYCE ne peut constituer une garantie non expressément écrite.
9. RESPONSABILITE
9.1 RESPONSABILITE DE PLAYCE
PLAYCE est responsable de la mise à disposition du Site à ses Utilisateurs. Sa responsabilité est donc strictement limitée à la mise en relation entre Professionnels du dépannage et des travaux et ses Utilisateurs.
PLAYCE réalise et transmet les Devis Provisoires sur la base des informations communiquées par l'Utilisateur et n'est pas responsable de son établissement. Par ailleurs, PLAYCE ne peut être tenu pour responsable des Devis, qu'ils soient Provisoire ou Finaux, réalisés par les Professionnels à destination des Utilisateurs.
9.2 RESPONSABILITÉ DU VISITEUR
Le Visiteur est seul responsable de l'utilisation du Site. Il est en outre tenu de respecter les présentes CGU, ainsi que les législations et réglementations en vigueur. À ce titre, PLAYCE n'est aucunement responsable des éventuels litiges survenant entre Utilisateur(s), Visiteur(s), Professionnel(s) et tiers, ainsi que des dommages ou plaintes, constatées comme avérées, découlant de l'utilisation du Site, et ce même lors de la réalisation de la Prestation.
9.3 LIMITATION DE RESPONSABILITÉ
PLAYCE fait tout son possible pour garder le site sécurisé il est rappelé que PLAYCE fournit le site en l'état. PLAYCE ne saurait être tenu pour responsable pour tout dommage direct ou indirect que le visiteur et/ou le professionnel subit/subissent, qu'il soit corporel, matériel, financier, et ce même si PLAYCE a été informé de la possibilité de la survenance de tels dommages.
Il est également rappelé que les Utilisateurs et les Professionnels sont seuls responsables de la légalité de leurs actes dans le cadre de l’utilisation du Service. PLAYCE décline donc toute responsabilité quant aux conséquences directes et/ou indirectes de la mise en relation entre les Professionnels et les Utilisateurs ainsi qu'aux éventuels manquements du Professionnel dans le cadre de la gestion de sa Commande et de sa relation avec l'Utilisateur.
Il est en outre rappelé que PLAYCE, en sa simple qualité d'intermédiaire, n'est aucunement responsable des éventuels litiges survenant entre Utilisateur(s), Visiteur(s), Professionnel(s) et tiers, ainsi que des dommages ou plaintes, constatées comme avérées, découlant de l'utilisation du Site, et survenant avant, pendant et après la réalisation de la Prestation.
Enfin, étant précisé que PLAYCE fait appel à un Prestataire pour l'encaissement pour compte du Professionnel, la Société ne saurait être tenue pour responsable en cas d'incident ou dysfonctionnement quelconque dans le processus de paiement, d'encaissement ou de transfert des fonds dudit Prestataire au Professionnel.
10. PROPRIETE INTELLECTUELLE
Les présentes CGU n'emportent aucune cession d'aucune sorte de droits de propriété intellectuelle sur les éléments appartenant à PLAYCE et/ou à ses concédants au bénéfice d’un Utilisateur et/ou d’un Visiteur.
Les droits de propriété intellectuelle (tels que notamment droits d'auteur, droits voisins, droits des marques, droits des producteurs de bases de données) portant tant sur la structure que sur les contenus du Site et notamment les images, sons, vidéos, photographies, logos, marques, éléments graphiques, textuels, visuels, outils, logiciels, documents, données, etc. (ci-après désignés dans leur ensemble " Éléments ») sont réservés.
Ces Éléments sont la propriété de PLAYCE et sont mis à disposition des Utilisateurs, à titre gracieux, pour la seule utilisation du Service et dans le cadre d'une utilisation normale de ses fonctionnalités.
Toute utilisation non expressément autorisée des Éléments du Site Internet entraîne une violation des droits d'auteur et constitue une contrefaçon. Elle peut aussi entraîner une violation des droits à l'image, droits des personnes ou de tous autres droits et réglementations en vigueur. Elle peut donc engager la responsabilité civile et/ou pénale de son auteur.
Il est interdit à tout Utilisateur de copier, modifier, créer une œuvre dérivée, inverser la conception ou l'assemblage ou de toute autre manière tenter de trouver le code source, vendre, attribuer, sous licencier ou transférer de quelque manière que ce soit tout droit afférent aux Éléments.
Tout utilisateur du service PLAYCE s’engage notamment à ne pas :
Intégrer tout ou partie du contenu du site internet dans un site tiers, à des fins commerciales ou non ;
Utiliser un robot, une application de recherche ou tout autre moyen permettant de récupérer ou d’indexer tout ou partie du contenu du site internet excepté en cas d’autorisation expresse et préalable donnée par écrit par PLAYCE.
Copier les informations sur des supports de nature permettant de reconstituer tout ou partie des fichiers d’origine.
Toute reproduction, représentation, publication, transmission, utilisation ou modification, extraction, de tout ou partie des Éléments et ce de quelque manière que ce soit, faite sans l'autorisation préalable et écrite de PLAYCE est illicite. Ces actes illicites engagent la responsabilité de ses auteurs et sont susceptibles d'entraîner des poursuites judiciaires à leur encontre et notamment pour contrefaçon.
Les marques et logos PLAYCE sont des marques déposées. Toute reproduction partielle ou totale de ces marques et /ou logo sans l’autorisation préalable et écrite de PLAYCE est interdite. En tant que producteur de bases de données du service PLAYCE, la société interdit l’extraction et/ou la réutilisation de la ou des bases de données au sens de l’article L342-1 et L342-2 du code de la propriété intellectuelle. PLAYCE se réserve la possibilité de saisir toutes voies de droit à l’encontre des personnes qui n’auraient pas respecté les interdictions contenues dans cet article.
Vous acceptez de défendre et d'indemniser PLAYCE (y compris pour les frais d'avocats) ainsi que les mandataires sociaux, administrateurs, agents et employés de PLAYCE contre toute demande ou réclamation faite par un tiers, causée ou résultant d'une violation de votre part des présentes Conditions Générales ou de tout document qui y est incorporé par référence, ou d'une violation de votre part de toute loi ou de tout droit de ces tiers.
11. MODALITE DE PAIEMENT
Pour les Prestations de dépannage d'urgence, l’Utilisateur, après avoir suivi le processus indiqué à l’étape 4 de l’article 5 des présentes CGU, autorise PLAYCE à bloquer le montant correspondant au plafond du Devis Provisoire communiqué par PLAYCE.
Pour les Prestations de travaux, l’Utilisateur, après avoir suivi le processus indiqué à l’étape 4 de l’article 5 des présentes CGU, autorise PLAYCE à bloquer le montant correspondant à l'acompte du plafond du Devis Provisoire communiqué par PLAYCE.
Après réception par PLAYCE du Devis Final du Prestataire dûment signé par le Professionnel et l’Utilisateur ayant passé la Commande, le montant indiqué dans le Devis Final sera prélevé sur le compte de l'Utilisateur via un système de paiement opéré par un Prestataire de PLAYCE et fonctionnel sur le site www.letsplayce.com. Ledit Prestataire procédera au versement de la somme séquestrée auprès du Professionnel selon les modalités du contrat de partenariat entre PLAYCE et le Professionnel, notamment des conditions financières.
L’Utilisateur, après avoir suivi le processus indiqué à l’Etape 4-2 de l’article 5 des présentes CGU, et après réception par PLAYCE du Devis Final du Professionnel dûment signé par le Professionnel et l’Utilisateur ayant passé la commande, le montant indiqué dans le Devis Final sera prélevé sur le compte de l'Utilisateur via un système de paiement opéré par un Prestataire de PLAYCE montant indiqué dans le Devis Final et il sera procédé au versement de la somme séquestrée auprès dudit Professionnel selon les modalités du contrat de partenariat entre PLAYCE et le Prestataire, Professionnel, notamment des conditions financières.
11.3 Il est rappelé que le Professionnel ne pourra modifier le montant d’un Devis Provisoire au-delà du plafond qu’en raison d’un motif légitime lié à une erreur de diagnostic lors de la Commande et/ou de l’établissement du Devis Provisoire, après accord préalable de l’Utilisateur et après en avoir informé  préalablement PLAYCE.  Le Professionnel s'engage par ailleurs à mettre à jour le montant de Devis Provisoire sur le site dans l'espace prévu à cet effet.
11.4 En tout état de cause, en cas d’annulation par l’Utilisateur de sa commande et dans l’hypothèse où un Professionnel s’est déplacé en vue de réaliser la Prestation,  l’Utilisateur est tenu de verser un somme de cinquante (50) euros afin d’indemniser ledit Professionnel.
12. TRACABILITE, DONNEES A CARACTERE PERSONNEL ET COOKIES
PLAYCE garantit être en conformité avec les lois et réglementations relatives à la protection des données personnelles. Il est acté que la passation de Commande par un Utilisateur nécessite la communication par l’Utilisateur de données à caractère personnel, notamment via le service de géolocalisation proposé par PLAYCE. L’Utilisateur peut désactiver les services de géolocalisation proposé par le Site mais accepte à ce titre que le fonctionnement de tout ou partie du Service peut être affecté. Il est rappelé à que l’Utilisateur s'engage à ne communiquer que des informations exactes et licites lors de sa Commande. Ce principe s'applique également à l'ensemble de l'utilisation du Service.
Les données à caractère personnel transmises lors de la passation de Commande, sont exploitées par PLAYCE afin de d'assurer à l’Utilisateur une mise en relation de ce dernier avec le Professionnel sélectionné. En particulier, PLAYCE s’engage à ne pas transmettre les données à caractère personnel des Utilisateurs à d'autres tiers que les Professionnels susceptibles et capables de répondre à une Commande. Les informations enregistrées sont réservées à l’usage du service concerné. Conformément aux articles 38 à 40 de la loi n° 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, toute personne peut obtenir communication et, le cas échéant, rectification ou suppression des informations la concernant, en s’adressant à la société PLAYCE. Toute personne peut également, pour des motifs légitimes, s’opposer au traitement des données la concernant.
Pour exercer ce droit, les utilisateurs peuvent écrire par courrier au siège social de l’entreprise ou par mail à l’adresse contact@letsplayce.com. Playce fera tout son possible pour satisfaire dans les meilleurs délais aux demandes qui lui parviendraient.
A des fins de preuve, il est précisé que des données relatives à l’Utilisateur peuvent être conservées et archivées de manière confidentielle par PLAYCE ou tout tiers mandaté par PLAYCE, pour une durée fixée par MESDEPANNEURS.FR à l’occasion des formalités de déclaration auprès de la C.N.I.L et au maximum pour la durée de prescription de droit commun des actions civiles en vertu de l'article 2224 du Code civil. Conformément à la loi N°78- 17 du 6 janvier 1978 dite « Loi Informatique et Libertés » et l’ensemble des modifications apportées depuis s’y rattachant directement, PLAYCE a fait l’objet d’une déclaration auprès de la Commission Nationale de l’Informatique et des Libertés (CNIL) sous le numéro : 1705194.
PLAYCE conserve par ailleurs l’historique des connexions des Utilisateurs au Service dans le respect des délais réglementaires qui lui sont imposés.
L’Utilisateur accepte et autorise PLAYCE à communiquer à des tiers toute information le concernant, si cette communication est raisonnablement nécessaire pour se conformer aux lois et règlement en vigueur et ou à toute réquisition ou requête judiciaire ou administrative, pour se protéger ou protéger toute autre personne.
La prospection commerciale par courrier électronique est autorisée dans les conditions prévues par la loi si les coordonnées du destinataire ont été recueillies dans le respect des dispositions de la loi n° 78-17 du 6 janvier 1978 modifiée.
L’Utilisateur reconnaît la possibilité pour PLAYCE ou tout tiers mandaté par PLAYCE Google par exemple, d'utiliser la technique des cookies ou toute autre technique assimilée permettant de tracer sa navigation sur le Site et de collecter ainsi les données le concernant.
L’Utilisateur dispose de la faculté de s'opposer, sans frais, à ce que les données le concernant soient utilisées à de telles fins.
13. SITES INTERNET TIERS
TPLAYCE n’approuve ni ne contrôle les sites Internet tiers auxquels l'Utilisateur peut avoir accès en cliquant sur des liens hypertexte. PLAYCE ne saurait être à ce titre tenu pour responsable du contenu ou des opérations de tous les sites Internet tiers accessibles depuis le Site. PLAYCE conseille au Visiteur de s’informer sur les pratiques opérées par les sites tiers, notamment via la prise de connaissance ses conditions générales d'utilisation ou de vente desdits sites.
Les communications, relations commerciales, participation aux promotions ou aux publicités accessibles depuis le Site ainsi que la livraison et le paiement de produits et services et tous termes, conditions, garanties ou déclarations y afférents, lient le Visiteur exclusivement avec l’annonceur. À cet égard, le Visiteur reconnaît et accepte que PLAYCE ne saurait en aucun cas être responsable de toute perte ou dommage quels qu’ils soient, encourus lors ou consécutivement à de telles négociations, ou résultant de la présence sur le Site de tels annonceurs.
15. SUSPENSION ET RESILIATION
PLAYCE se réserve le droit, en cas de non-respect des présentes CGU, d'informer l’Utilisateur de ce manquement en lui demandant d’y remédier dans les plus brefs délais, et/ou de suspendre ou annuler la Commande effectuée par l’Utilisateur sans indemnité ni préavis.
16. CONFIDENTIALITE
PLAYCE considère les informations transmises ou recueillies par PLAYCE à l'occasion de l’utilisation du Service comme confidentielles et s'engage à ne pas les communiquer à l'extérieur, sauf mention contraire dans les présentes CGU.
17. STIPULATIONS DIVERSES
Dans l'hypothèse où une ou plusieurs modalités figurant dans les Conditions Générales seraient considérées comme illégales, inopposables ou inapplicables par une décision de justice, les autres stipulations des Conditions Générales resteront en vigueur, à la condition que l'économie générale du contrat n'en soit pas bouleversée.
Les CGU constituent l’intégralité des accords entre les Visiteurs et PLAYCE et prévalent sur toute stipulation orale ou écrite antérieure ou contemporaine et relative au même objet.
PLAYCE se réserve le droit d’amender les CGU à tout moment et par quelque moyen que ce soit.
PLAYCE peut céder ou transférer à tout tiers, sans notification préalable, ses droits et obligations découlant des CGU.
Aucune des Parties ne saurait être responsable de la non-exécution de ses obligations au titre des CGU, en cas de survenance d’un événement de force majeure, tel que défini par les juridictions françaises.
Le fait pour l’une des Parties de ne pas se prévaloir de l’une quelconque des stipulations des CGU ne saurait être interprété ultérieurement comme une renonciation à la stipulation en cause. Toute renonciation n’est effective qu’en cas de modification des CGU conforme aux termes de l’article 1 ci-dessus.
Enfin, les fichiers, données, informations et registres informatisés enregistrés dans les systèmes informatiques de PLAYCE seront admis comme preuve des actes et faits intervenus entre les  Parties. La conservation des registres sera présumée, sauf preuve contraire, avoir eu lieu dans des conditions raisonnables de sécurité si les messages, données et autres documents sont enregistrés systématiquement sur un support fiable et durable.
18. DROIT APPLICABLE ET LITIGES
Les présentes Conditions Générales sont régies et interprétées conformément au droit français. Les tribunaux français auront compétence pour se prononcer sur tous les litiges susceptibles de naître entre les parties relatifs à l'exécution des présentes



</p>




				</div>
            </div>
        </div>
    </section>
<?php include('footer.php');?>